### ISSUE TITLE
Remove dependency on gorilla context

### ISSUE THREAD

**Issue by pjebs** [GoIncremental/negroni-sessions#16]
Do you think it's time to remove dependency on gorilla context?

Even the authors of gorilla context suggest it's time to either use it OR use the standard library context, **BUT** not both since they interfere with each other: http://www.gorillatoolkit.org/pkg/context

Given that the rest of the Go community is starting to use std lib context, it's making it difficult to move on for me because I rely on this library which uses gorilla context.

**Comment by Bochenski** [comment]
Agreed we should switch to std lib.  Not sure when I'll have time to do it - but a PR would be welcome.
